
- name: Download SecLists
  shell: cd /usr/share/wordlists/; git clone https://github.com/danielmiessler/SecLists.git
  ignore_errors: True

- name: Download brutespray
  shell: cd /usr/share/wordlists/; git clone https://github.com/x90skysn3k/brutespray.git
  ignore_errors: True

- name: Copying local wordlists
  copy:
    src: "{{ item }}"
    dest: '/usr/share/wordlists/'
  with_fileglob:
    - "wordlists/*"

- name: Update the database
  shell: updatedb
  ignore_errors: True
